version: '3.8'

services:
  backend:
    build:
      context: ./backend-setaldakar
    container_name: backend-api
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./soutenance_frontend
    container_name: frontend-app
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
